version: '3.3'
services:
  mongo:
    ports:
      - '27017:27017'
    container_name: JobPortal
    restart: always
    environment:
       MONGO_ININTDB_DATABASE: jobPortal
       MONGO_INITDB_ROOT_USERNAME: mongoadmin
       MONGO_INITDB_ROOT_PASSWORD: admin
    image: mongo