spring:
  data:
    mongodb:
      host: 'localhost'
      port: 27017
      database: 'jobPortal'
      username: 'mongoadmin'
      password: 'admin'
      authentication-database: 'admin'
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: 'DEBUG'
token:
  signing:
    key: "Fsfmdisfesesifmdismfmesfmesifmrdgjrmgieosmfiordmgiordmfesmf"